### ISSUE TITLE
EPIC: Build voter success metrics into the app

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#1013]
Avoids the separate effort of trying to collect them later.

# voter success metrics

Leaving aside for the moment my choice of words, I think these are the categories I'd like to capture, that might help with the analysis.

Question one (muliple choice, one answer) As a voter, I was motivated to vote tactically / voteswap mostly by:

- my preferred party looking very likely to lose in my constituency
- my preferred party looking very likely to win in my constituency.
- electoral reform more than by preferred party
- closely following the advice of a tactical voting campaign
- defeating a party
  - supplementary and optional question for 'defeating': which party did you want to defeat
  - supplementary and optional question for 'tactical': which campaign were you following

Question two (muliple choice, one answer) As a voter, in choosing a swap, I was most motivated by:

- getting to vote where I can make a difference to my preferred party's chances in a marginal
- getting to vote where my preferred party fairly certain to win
- getting to vote where my preferred party matched a tactical voting campaign. 
- getting to vote where I can make a difference to defeating a party
  - supplementary question for confirmed swaps: did your chosen swap meet your criteria at the point you chose/confirmed it

Question three (true/false) As a voter, before choosing a swap, I was motivated by:
- offering to swap because my constituency looks like a good opportunity for voters for my willing party 

Other true/false questions:

For confirmed swaps:

We should also ask people who swapped whether

- they tried to contact their partner (true/false)
- they received contact from their partner (true/false)
- they had a conversation with their partner (true/false)
- if so, was that conversation useful (true/false)

- would you have been willing to be flexible and offer to vote tactically for more than just one party (true/false)

**Comment by aspiers** [comment]
See also #993 and #994 for questions / metrics / analysis specific to GE2024.

A few quick thoughts here:

- To maximise the chances of getting users to voluntarily answer a survey, we should keep it as short and punchy as possible.
- If there are any of these questions we can answer or deduce ourselves using our existing data, rather than asking users, then we should do that.
- We should carefully consider when is the right stage to ask each question.  There might be some which can be asked inline as part of the app's flow, but others are probably best asked after the election is over.
- For questions in the latter camp, perhaps we should send an email out linking to a simple one-page in-app survey which is largely yes/no or multiple choice, with a freeform text field at the end in case they want to give any other feedback not captured by the questions.
- If users don't fill out the form in the first week or two after sending the initial email, we could send a reminder email.

Cc @tdg

**Comment by baob** [comment]
> There might be some which can be asked inline as part of the app's flow,

It was those I was think of here. What can we add to the app (as optional questions, supplementing what we can already infer) as part of the normal flow of events.

**Comment by baob** [comment]
Actually, I do need to re-think this ... will probably be re-worked as another issue 'capture voter **motivations** as part of app flow'

**Comment by baob** [comment]
Added new issue that better captures what I was thinking of. -> https://github.com/swapmyvote/swapmyvote/issues/1021

I think this new issue addresses most of your comments @aspiers, except that in raising _this_ issue I was never really thinking of collecting answers after the election. It looked like I was, from the original text, because I was a bit lazy in my cut'n'paste of text from elsewhere.

We can raise another ticket for post-election survey. I'm closing this one now, superseded by the other.
