### ISSUE TITLE
Allow users to share email address with confirmed partners

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#102]
This covers both the implementation and the proper obtainment of consent, for which previous discussion was captured in #74.

**Comment by aspiers** [comment]
Phew - turns out we already explicitly covered sharing email (and even phone number) with swap partners in the Personal Data section of the privacy policy pre 2019 launch.

So this issue is more about making it possible and explicit in the UI.  Extra attention is needed in the Facebook/Twitter login cases since sharing email is not as expected there.

**Comment by baob** [comment]
I was going to work on this by adding a consent column to the users table, and associated form changes, but it seems from recent changes to policy wording on the website (on email login branch), there's nothing to do here.

**Comment by aspiers** [comment]
That's not right, we need to track consent server side. This is
complicated, had a long chat with Tom about it last night.

**Comment by baob** [comment]
This is my proposal:
https://github.com/swapmyvote/swapmyvote/issues/324

**Comment by baob** [comment]
@tdg @aspiers  with #324 and #337 now closed I think we can say this one is done ?

**Comment by aspiers** [comment]
Agreed!! Stellar work
