### ISSUE TITLE
Build 'job' template to email all users who meet certain criteria

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#306]
Eg #302 #298 etc

**Comment by aspiers** [comment]
We can already do this by copying the approach in https://github.com/swapmyvote/swapmyvote/blob/master/lib/tasks/users.rake so let's deal with this on a case by case basis.  I was originally thinking that we could use https://www.mailgun.com/email-templates/ so that @tdg could edit the email templates himself, but we'd still need Ruby code to select the right audience, so this doesn't gain much, plus it loses the ability to use HAML partials for standard headers / footers / helpers etc.
