### ISSUE TITLE
Update user-facing text for GE2019

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#34]
Some of the web/email text still needs to be updated for GE2017.  Most of this is in the email templates, but there might be one or two bits of the web UI which need updating too.  @tdg This is something you could definitely help with.

**Comment by aspiers** [comment]
#50 probably tackled most of this.  @tdg What's left to do?

**Comment by tdg** [comment]
Copy is up to date for 2019 but 2017 system, so just need to update mailers etc in light of recent system improvements before launch (and subsequently)

**Comment by aspiers** [comment]
@tdg wrote:
> Copy is up to date for 2019 but 2017 system

Sorry not sure what you mean, was that a typo?

**Comment by tdg** [comment]
> Sorry not sure what you mean, was that a typo?
Just that I've corrected mistakes and updated copy since 2017 eg to reflect the 2017 (rather than 2015) _political_ result, etc. 

However, I will need to do another copy pass just before launch to reflect changes we make in the system before launch _this time_ - it seems like the best time to do that is once changes have been made.

So for example we will hopefully include 
- [ ] a piece of copy about phone numbers ( #7 )
- [ ] update the piece on trust
etc

We may also need to draft any SMS communications?

**Comment by aspiers** [comment]
At least some of the above items sound like more worrying about features we haven't implemented yet ;-)  As per yesterday's chat let's not do that.

Are there any copy changes we know for sure that are needed right now?
