### ISSUE TITLE
Prepare for closed-wind-down mode

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#376]
- [ ] Make sure `closed-wind-down` mode prevents all user activity
- [ ] Make sure it shows appropriate text on home page

**Comment by tdg** [comment]
My draft copy. I like yours too. But needs to keep people interested in what’s next so I’ve gone for immediate death and rebirth rather than slow goodbye. 


Swap My Vote is currently closed for swaps. We will run again for the next General Election, whenever that turns out to be. 

The work doesn’t stop here. The team behind Swap My Vote, Forward Democracy [forwarddemocracy.com], will continue to develop ways to defend and develop our democracy, that most precious, powerful, and fragile of things. 

Please enter your email address for reminders when we open again for swaps, updates, news, and campaigns that could help to defend and develop democracy, electoral reform and digital democratic tools. You can unsubscribe at any time from the link in the footer of any of these emails

Email Address:
This field is required.
Follow us on Twitter Like us on Facebook Donate on Crowdfunder
