### ISSUE TITLE
Protect voters' data better before swap - redact part of name

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#47]
![Screen Shot 2019-11-06 at 18 37 04](https://user-images.githubusercontent.com/95868/68327013-797c4a00-00c4-11ea-9fc1-9eaccb4f93dc.png)
Ideal would be to keep first name and second initial. 

However, names don't all follow the same rules, so could we redact the last `50%-1` of characters? Better ideas welcome

**Comment by aspiers** [comment]
We only store the full name in the database, not first and surname separately.  This is because omniauth-twitter only provides the full name even though omniauth-facebook provides both.  Twitter doesn't even require a human name so it could literally be any string of text the account owner feels like setting.  So yeah, we'd need to invent some heuristic for guessing how to anonymise.

**Comment by aspiers** [comment]
I just realised that there is only a point to attempting this anonymization because you don't get a link to your partner's social profile until you have both agreed to the swap.  This eliminates the possibility of picking the best swap candidate by combing through social profiles but I guess that's necessary for the level of privacy we want.

**Comment by tdg** [comment]
I think we agree on this

**Comment by aspiers** [comment]
Can you help me decide how this should be implemented? What do you mean by `50%-1`?

**Comment by egglestn** [comment]
We could do a solution based on presence of space in the name: if there's no space, use the whole name. If there is a space, strip from the second character after the space. This could be slightly odd for cultures where the surname comes first (we'll end up stripping the first name), but if we don't know which is which, there is not much choice: this is primarily a UK app.

Going back to an earlier comment, I think it's still worth doing, because it will mean that you won't see the full social profiles for the people you decide not to swap with.

**Comment by aspiers** [comment]
@egglestn Great idea, I think that's perfect for M0. Later we could allow the user to choose their own display name, initially setting it using this logic.

**Comment by aspiers** [comment]
@threedaymonk Any chance you could look at this one? Should be very easy in theory!

**Comment by threedaymonk** [comment]
> @threedaymonk Any chance you could look at this one? Should be very easy in theory!

Yes, I'm free from tomorrow, and I had my eye on this!

**Comment by aspiers** [comment]
Bloody brilliant, thanks so much!  If it's as quick and easy as I think it should be, #76 is also super urgent and doesn't have anyone assigned right now.
