### ISSUE TITLE
Some change around time of #789 (erroneous source) had detrimental impact on DB speed on sqlite3

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#811]
A run of db:seed on an already populated database (minimal writes therefore) used to run in about 30 seconds.

After merge of #789 it now take 6 minutes.

Reverting #789 hasn't helped however, it's like some option has been switched in sqllite outside the tables, even db:drop followed by db:setup doesn't clear the issue. 

/cc @aspiers 

EDIT: Even though it happened after I pulled the #789 change, seems hardly likely this was the trigger, much less the cause, since I have no way to revert the change as yet.

**Comment by aspiers** [comment]
Based on the above, it sounds like this is unlikely to have been caused by #789.  Feels more likely to me it's related to #675 because we know that the TV recommendation seeding process is extremely expensive (multiple queries per recommendation), so the more recommendation campaigns we incorporate (currently 6), the slower the seeding process gets.

I would suggest closing because I'm not sure there's much more we can do here which isn't already covered by #675.

**Comment by baob** [comment]
This is not really about the general slowness of seeding, it was a specific perhaps 3-fold slowdown on my personal mac. Not traceable to any code change though, so I have to close.
