### ISSUE TITLE
BUG: willing/preferred party are lost during sign-up

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#824]
Steps:

* From home page of SMV, choose willing/preferred party
* you're asked to fill in email and password
* ~make the two passwords different, save~
* ~passwords rejected, so make them match, save~
* (choose constituency)
* now you are asked willing/preferred party again.

**Comment by aspiers** [comment]
This is happening even without doing anything wrong in the flow.

**Comment by aspiers** [comment]
This is breaking the API too.  The API correctly prepopulates the form on the home page prior to login, but after sign-up, those values are lost, just as if the user had manually selected them rather than via prepopulation from the API .

**Comment by baob** [comment]
> This is breaking the API too.

Yes, I fully expected that, didn't test for it.

**Comment by aspiers** [comment]
I think this is how it's _supposed_ to work:

https://github.com/swapmyvote/swapmyvote/blob/3475aed13fde5b82961a620d830df5ab771a5cd4/app/controllers/users/sessions_controller.rb#L12-L31

**Comment by aspiers** [comment]
I have found a change which I'm a bit suspicious of:

https://github.com/swapmyvote/swapmyvote/commit/8a4b078862ce708a93db3356e09257d293899e3f

Admittedly this problem was reported 2 weeks ago and this change is not that old, so maybe there are additional problems lurking behind it.  But there's no getting around the fact that it changes [a `POST` `formaction`](https://github.com/swapmyvote/swapmyvote/commit/8a4b078862ce708a93db3356e09257d293899e3f#diff-e67e56b65817826c0db345725c069e715ac003a4924034910e001015e5acfac2L31) to a [`window.location.assign`](https://github.com/swapmyvote/swapmyvote/commit/8a4b078862ce708a93db3356e09257d293899e3f#diff-7ad9acaf8f76ede9d0ba0fcf552faf830ff5b925b9b080b2be0bcede863e5f56R43) which I assume results in a `GET` not a `POST`.  And after this `window.location.assign` I can't see any evidence of the user's party choices persisting on the sign-up page either in `params` or `session`.

Bearing mind the above comment, it seems clear that this whole process relies on a `POST` not a `GET` to preserve the party choices, so I think that's a good place to start investigation.  Perhaps reverting to the commit before this one and seeing whether the choices get passed to the sign-up page (and beyond) is the best next step, but I've run out of time.

@stevebaxter This is your wheelhouse for sure, but if @baob gets to it first then great.

**Comment by aspiers** [comment]
Another thing to check with high priority: I _think_ that if the constituency is set via API then at least that makes it all the way through fine.  So how the hell would it work for constituency but not the parties?

**Comment by aspiers** [comment]
Actually another thought - the sessions controller isn't even relevant during sign-up is it... that's the registrations controller.  In which case the above snippet about abusing REST POST isn't relevant during sign-up either.

**Comment by stevebaxter** [comment]
That could be it though - the data must get from that form to the controller somehow. I'll try and have a look, but sadly probably won't be before tomorrow.
