### ISSUE TITLE
Just ONE traffic cop needed to decide what the user sees based on current state.

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#980]
So we don't have decisions like this implemented in a bunch of different places and cause loops (#933, #931) ... everything goes via the traffic cop.

> When there are no swaps available, there's no other call to action so it makes sense to capitalise on the waiting time to get the user to verify their mobile, so that they're ready to swap when a partner materialises.

(from https://github.com/swapmyvote/swapmyvote/pull/947#issue-2387389873 )

**Comment by aspiers** [comment]
Sorry for ignorance, what the hell is a single traffic cop :laughing:

**Comment by baob** [comment]
ONE PLACE that decides what the user sees next.

**Comment by aspiers** [comment]
I don't really get how this is achievable with Rails?  It's fundamentally built on the concept of multiple routes and multiple controllers, each of which can redirect as it chooses.

Personally I would prefer to invest time into writing automated integration tests via Cypress rather than a big rewrite of core flow logic (although maybe that's not what you're proposing here - not sure I understand the proposal exactly).

**Comment by baob** [comment]
Looks like I chose a poor way to express myself. 

This is what I've seen and am suggesting one way of avoiding it.

Coder writes logic for

    When A is finished, go to B

However he is thwarted in an edge case because 2 years before another coder wrote

    When you arrive at B, if we have condition Y, go to C.

B was the right destination (things changed since 2 years ago), but it only works sometimes.


But yes .... the driver behind any change of routing behaviour should be integration tests that flow through 2 or more action.

**Comment by aspiers** [comment]
Don't get me wrong, I totally understand the benefit of consolidating this logic in one place, and I'm not disputing that would have value.  I just don't know how that could be achieved within the constraints of the Rails framework, at least not without a major rewrite (e.g. put everything in a single controller).  If you have concrete suggestions for how to do it then I'm all ears!  It's entirely possible I'm missing something obvious.

**Comment by baob** [comment]
It could be that I'm missing a difficulty in implementation :) 

Anyway ... should probably close as it's a (potential) architectural solution to a problem. And we can avoid the problem by writing tests to ensure correct routing, so long as we can write tests that nail down scenarios involving actions from different controllers.

**Comment by aspiers** [comment]
[**@baob**](https://github.com/baob) commented on [Oct 26, 2024, 5:46 PM GMT+1](https://github.com/swapmyvote/swapmyvote/issues/980#issuecomment-2439651624 "2024-10-26T16:46:40Z - Replied by Github Reply Comments"):
> It could be that I'm missing a difficulty in implementation :)

If you have concrete suggestions then I'd love to hear them.  Until then I'm struggling to see anything clearly actionable here.

> Anyway ... should probably close as it's a (potential) architectural solution to a problem. And we can avoid the problem by writing tests to ensure correct routing, so long as we can write tests that nail down scenarios involving actions from different controllers.

Yeah, I think we need these tests anyway, regardless of how we architect the flows, and I'd always prefer to build tests before changing stuff rather than after.

**Comment by baob** [comment]
Not actionable.
